defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 33e6ae70-e937-4eb1-a5cd-875574a5fe61 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  354c36f9-da48-4330-8419-521a98caf71e: # Atelier Decoene
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
